### ISSUE TITLE
No path path provided error since version 2.6.2

### ISSUE THREAD

**Issue by bgaillard** [zendframework/zend-mvc#75]
Hi, we encounter the following error since we updated our project to version 2.6.2 (for now we've reverted our conf to version 2.6.1 which is working). 

Here is the error we encountered (we've changed nothing in our configuration to see this appear). 

```
Fatal error: Uncaught exception 'Zend\View\Exception\RuntimeException' with message
'No base path provided' in vendor\zendframework\zend-view\src\Helper\BasePath.php:38

Stack trace:
#0 [internal function]: Zend\View\Helper\BasePath->__invoke('css/styles.less')
#1 vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(393): call_user_func_array(Object(Zend\View\Helper\BasePath), Array)
#2 module\Application\view\layout\layout.phtml(15): Zend\View\Renderer\PhpRenderer->__call('basePath', Array)
#3 module\Application\view\layout\layout.phtml(15): Zend\View\Renderer\PhpRenderer->basePath('css/styles.less')
#4 vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(501): include('C:\\dev_tools\\wa...')
#5 vendor\zendframework\zend-view\src\View.php(205): Zend\View\Renderer\PhpRenderer->render(O in vendor\zendframework\zend-view\src\Helper\BasePath.php on line 38
```

Is their something we've misconfigured in our project ? Or this a critical bug which have to be fixed ? 

Thanks.

**Comment by bgaillard** [comment]
Ok, I finally found the cause of the problem, because of 2 other Zend bugs we forced the versions of `zendframework/zend-view (2.5.3)` and `zendframework/zend-cache (2.5.3)`. 

If we let `zend-view` and `zend-cache` be updated to the last version then it works. 

So I close this issue.
